name: Push to Artifact Registry

on:
  push:
    branches:
      - main

env:
  VERSION: ${{ github.sha }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: nestjs-crud-sample
  REGION: ${{ vars.REGION }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@latest
      - name: Configure Docker
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet
      - name: Build the Docker image
        run: docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_TAG} .
      - name: Push the Docker image to Artifact Registry
        run: docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${IMAGE_NAME}:${IMAGE_TAG}